package: media_srcset
version: '2.0'
author: 'FriendsOfRedaxo'
supportpage: www.redaxo.org/de/forum/

pages:
    media_manager/srcset_settings:
        title: 'media_srcset'


requires:
    packages:
        media_manager: '>=2.5.6'
    redaxo: '>=5.4.0'

